### ISSUE TITLE
Enable markmove syntax from chessboard package in xskak

### ISSUE THREAD

**Issue by Korosensei42** [u-fischer/xskak#5]
Currently I try to use the animation the xskak package offers, but I would like to use the [markmove syntax from the chessboard package](http://www.home.uni-osnabrueck.de/elsner/Skripte/Material/Latex/Dokumentation/Chess_Board_by_Ulrike_Fischer.pdf) within xskak, since I find it less convoluted.
Currently this possibility seems not to be there.

Would this be possible to do in a timely manner or is this idea too ambitious?

Best regards

**Comment by u-fischer** [comment]
sorry I have no idea what you mean. Please demonstrate with a small, complete document.

**Comment by Korosensei42** [comment]
Turns out I was too dumb to realize a simple syntax mistake I did.
Nevertheless [here](https://github.com/u-fischer/xskak/files/4707448/MinimalChangeArrowSyntax.txt) is the tex-code as a textfile (git comments seem not to support tex files) stating what I wanted to do and what ended up working. Sorry for the noise.
