### ISSUE TITLE
How to use letter notation instead of symbols?

### ISSUE THREAD

**Issue by rfetick** [u-fischer/xskak#8]
Hello,

First of all, thanks a lot for your work!
I was just wondering if it is possible to use the letter notation (e.g. `Ke2`) instead of the pieces symbols when printing the `\mainline`. I couldn't see this in the documentation. Sorry if this information effectively appears in the doc and I missed it.

Kind regards,

Romain

**Comment by u-fischer** [comment]
Do not use the issue tracker for support. Better ask on sites like tex.stackexchange. 
You can use `\usetextfig \settextfiglanguage{german}`, see http://mirrors.ctan.org/macros/latex/contrib/chessfss/chessfss.pdf

**Comment by rfetick** [comment]
Thank you, it works perfectly!
I will follow your advice and use `tex.stackexchange` next time I need to do so.
